INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) VALUES (101,'TCS',1400.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) VALUES (102,'HDFS',140.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) VALUES (103,'HCL',900.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) VALUES (104,'INFOSYS',200.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) VALUES (105,'MICROSOFT',5000.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) VALUES (106,'HP',140.00);
INSERT INTO STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) VALUES (107,'MRF',1100.00);


